- hosts: localhost
  become: true
  pre_tasks:
    - name: update repositories
      apt: update_cache=yes
      changed_when: False
  tasks:
    - include: tasks/node-setup.yml
    - include: tasks/npm-packages.yml
    - include: tasks/core.yml
    - include: tasks/github-cli.yml
    - include: tasks/zsh.yml
    - include: tasks/nvim.yml
